/*
 * generated by Xtext 2.25.0
 */
package persons.tasks3.merger.mdsl;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MergerDslRuntimeModule extends AbstractMergerDslRuntimeModule {
	@Override
	public void configure(Binder binder) {System.out.println("i am in MERGER taskDSLRuntimeModule-----------------------------");
	super.configure(binder);
	//binder.bind(IScopeProvider.class).to(MyConcreteScopeProvider.class);
	}
}
