/*
 * generated by Xtext 2.25.0
 */
package persons.tasks3.merger.mdsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import persons.tasks3.merger.ui.internal.MergerActivator;

public class MergerDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MergerActivator.getInstance().getInjector("persons.tasks3.merger.mdsl.MergerDsl");
	}

}
