/*
 * generated by Xtext 2.25.0
 */
package persons.tasks3.merger.mdsl.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class MergerDslScopeProvider extends AbstractMergerDslScopeProvider {

}
