/*
 * generated by Xtext 2.25.0
 */
package persons.tasks3.merger.mdsl.ide;


/**
 * Use this class to register ide components.
 */
public class MergerDslIdeModule extends AbstractMergerDslIdeModule {
}
