/*
 * generated by Xtext 2.25.0
 */
package persons.tasks3.merger.mdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import persons.tasks3.merger.mdsl.MergerDslRuntimeModule;
import persons.tasks3.merger.mdsl.MergerDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MergerDslIdeSetup extends MergerDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MergerDslRuntimeModule(), new MergerDslIdeModule()));
	}
	
}
