/**
 * generated by Xtext 2.25.0
 */
package persons.tasks3.merger.mdsl.mergerDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see persons.tasks3.merger.mdsl.mergerDsl.MergerDslPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
} // Action
