/**
 * generated by Xtext 2.25.0
 */
package persons.tasks3.merger.mdsl.mergerDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Meeting Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link persons.tasks3.merger.mdsl.mergerDsl.MeetingAction#getTopic <em>Topic</em>}</li>
 * </ul>
 *
 * @see persons.tasks3.merger.mdsl.mergerDsl.MergerDslPackage#getMeetingAction()
 * @model
 * @generated
 */
public interface MeetingAction extends Action
{
  /**
   * Returns the value of the '<em><b>Topic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Topic</em>' attribute.
   * @see #setTopic(String)
   * @see persons.tasks3.merger.mdsl.mergerDsl.MergerDslPackage#getMeetingAction_Topic()
   * @model
   * @generated
   */
  String getTopic();

  /**
   * Sets the value of the '{@link persons.tasks3.merger.mdsl.mergerDsl.MeetingAction#getTopic <em>Topic</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Topic</em>' attribute.
   * @see #getTopic()
   * @generated
   */
  void setTopic(String value);

} // MeetingAction
