/**
 * generated by Xtext 2.25.0
 */
package persons.tasks3.merger.mdsl.mergerDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see persons.tasks3.merger.mdsl.mergerDsl.MergerDslFactory
 * @model kind="package"
 * @generated
 */
public interface MergerDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mergerDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.tasks3.persons/merger/mdsl/MergerDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mergerDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MergerDslPackage eINSTANCE = persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl.init();

  /**
   * The meta object id for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.PlanningImpl <em>Planning</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.PlanningImpl
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getPlanning()
   * @generated
   */
  int PLANNING = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANNING__NAME = 0;

  /**
   * The feature id for the '<em><b>Persons</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANNING__PERSONS = 1;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANNING__TASKS = 2;

  /**
   * The number of structural features of the '<em>Planning</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANNING_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.PersonImpl
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getPerson()
   * @generated
   */
  int PERSON = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NAME = 0;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.TaskImpl
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getTask()
   * @generated
   */
  int TASK = 2;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__ACTION = 0;

  /**
   * The feature id for the '<em><b>Persons</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__PERSONS = 1;

  /**
   * The feature id for the '<em><b>Prio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__PRIO = 2;

  /**
   * The feature id for the '<em><b>Dl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__DL = 3;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__UNIT = 4;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.ActionImpl
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getAction()
   * @generated
   */
  int ACTION = 3;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.LunchActionImpl <em>Lunch Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.LunchActionImpl
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getLunchAction()
   * @generated
   */
  int LUNCH_ACTION = 4;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LUNCH_ACTION__LOCATION = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Lunch Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LUNCH_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.MeetingActionImpl <em>Meeting Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MeetingActionImpl
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getMeetingAction()
   * @generated
   */
  int MEETING_ACTION = 5;

  /**
   * The feature id for the '<em><b>Topic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEETING_ACTION__TOPIC = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Meeting Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEETING_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.PaperActionImpl <em>Paper Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.PaperActionImpl
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getPaperAction()
   * @generated
   */
  int PAPER_ACTION = 6;

  /**
   * The feature id for the '<em><b>Report</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAPER_ACTION__REPORT = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Paper Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAPER_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.PaymentActionImpl <em>Payment Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.PaymentActionImpl
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getPaymentAction()
   * @generated
   */
  int PAYMENT_ACTION = 7;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_ACTION__AMOUNT = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Payment Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks3.merger.mdsl.mergerDsl.TimeUnit <em>Time Unit</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks3.merger.mdsl.mergerDsl.TimeUnit
   * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getTimeUnit()
   * @generated
   */
  int TIME_UNIT = 8;


  /**
   * Returns the meta object for class '{@link persons.tasks3.merger.mdsl.mergerDsl.Planning <em>Planning</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Planning</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.Planning
   * @generated
   */
  EClass getPlanning();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks3.merger.mdsl.mergerDsl.Planning#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.Planning#getName()
   * @see #getPlanning()
   * @generated
   */
  EAttribute getPlanning_Name();

  /**
   * Returns the meta object for the containment reference list '{@link persons.tasks3.merger.mdsl.mergerDsl.Planning#getPersons <em>Persons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Persons</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.Planning#getPersons()
   * @see #getPlanning()
   * @generated
   */
  EReference getPlanning_Persons();

  /**
   * Returns the meta object for the containment reference list '{@link persons.tasks3.merger.mdsl.mergerDsl.Planning#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.Planning#getTasks()
   * @see #getPlanning()
   * @generated
   */
  EReference getPlanning_Tasks();

  /**
   * Returns the meta object for class '{@link persons.tasks3.merger.mdsl.mergerDsl.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks3.merger.mdsl.mergerDsl.Person#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.Person#getName()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Name();

  /**
   * Returns the meta object for class '{@link persons.tasks3.merger.mdsl.mergerDsl.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks3.merger.mdsl.mergerDsl.Task#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Action</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.Task#getAction()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Action();

  /**
   * Returns the meta object for the reference list '{@link persons.tasks3.merger.mdsl.mergerDsl.Task#getPersons <em>Persons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Persons</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.Task#getPersons()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Persons();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks3.merger.mdsl.mergerDsl.Task#getPrio <em>Prio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prio</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.Task#getPrio()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Prio();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks3.merger.mdsl.mergerDsl.Task#getDl <em>Dl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dl</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.Task#getDl()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Dl();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks3.merger.mdsl.mergerDsl.Task#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.Task#getUnit()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Unit();

  /**
   * Returns the meta object for class '{@link persons.tasks3.merger.mdsl.mergerDsl.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for class '{@link persons.tasks3.merger.mdsl.mergerDsl.LunchAction <em>Lunch Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lunch Action</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.LunchAction
   * @generated
   */
  EClass getLunchAction();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks3.merger.mdsl.mergerDsl.LunchAction#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.LunchAction#getLocation()
   * @see #getLunchAction()
   * @generated
   */
  EAttribute getLunchAction_Location();

  /**
   * Returns the meta object for class '{@link persons.tasks3.merger.mdsl.mergerDsl.MeetingAction <em>Meeting Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Meeting Action</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.MeetingAction
   * @generated
   */
  EClass getMeetingAction();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks3.merger.mdsl.mergerDsl.MeetingAction#getTopic <em>Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Topic</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.MeetingAction#getTopic()
   * @see #getMeetingAction()
   * @generated
   */
  EAttribute getMeetingAction_Topic();

  /**
   * Returns the meta object for class '{@link persons.tasks3.merger.mdsl.mergerDsl.PaperAction <em>Paper Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Paper Action</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.PaperAction
   * @generated
   */
  EClass getPaperAction();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks3.merger.mdsl.mergerDsl.PaperAction#getReport <em>Report</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Report</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.PaperAction#getReport()
   * @see #getPaperAction()
   * @generated
   */
  EAttribute getPaperAction_Report();

  /**
   * Returns the meta object for class '{@link persons.tasks3.merger.mdsl.mergerDsl.PaymentAction <em>Payment Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Payment Action</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.PaymentAction
   * @generated
   */
  EClass getPaymentAction();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks3.merger.mdsl.mergerDsl.PaymentAction#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.PaymentAction#getAmount()
   * @see #getPaymentAction()
   * @generated
   */
  EAttribute getPaymentAction_Amount();

  /**
   * Returns the meta object for enum '{@link persons.tasks3.merger.mdsl.mergerDsl.TimeUnit <em>Time Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Time Unit</em>'.
   * @see persons.tasks3.merger.mdsl.mergerDsl.TimeUnit
   * @generated
   */
  EEnum getTimeUnit();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MergerDslFactory getMergerDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.PlanningImpl <em>Planning</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.PlanningImpl
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getPlanning()
     * @generated
     */
    EClass PLANNING = eINSTANCE.getPlanning();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLANNING__NAME = eINSTANCE.getPlanning_Name();

    /**
     * The meta object literal for the '<em><b>Persons</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLANNING__PERSONS = eINSTANCE.getPlanning_Persons();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLANNING__TASKS = eINSTANCE.getPlanning_Tasks();

    /**
     * The meta object literal for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.PersonImpl
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NAME = eINSTANCE.getPerson_Name();

    /**
     * The meta object literal for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.TaskImpl
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__ACTION = eINSTANCE.getTask_Action();

    /**
     * The meta object literal for the '<em><b>Persons</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__PERSONS = eINSTANCE.getTask_Persons();

    /**
     * The meta object literal for the '<em><b>Prio</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__PRIO = eINSTANCE.getTask_Prio();

    /**
     * The meta object literal for the '<em><b>Dl</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__DL = eINSTANCE.getTask_Dl();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__UNIT = eINSTANCE.getTask_Unit();

    /**
     * The meta object literal for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.ActionImpl
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.LunchActionImpl <em>Lunch Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.LunchActionImpl
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getLunchAction()
     * @generated
     */
    EClass LUNCH_ACTION = eINSTANCE.getLunchAction();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LUNCH_ACTION__LOCATION = eINSTANCE.getLunchAction_Location();

    /**
     * The meta object literal for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.MeetingActionImpl <em>Meeting Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MeetingActionImpl
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getMeetingAction()
     * @generated
     */
    EClass MEETING_ACTION = eINSTANCE.getMeetingAction();

    /**
     * The meta object literal for the '<em><b>Topic</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEETING_ACTION__TOPIC = eINSTANCE.getMeetingAction_Topic();

    /**
     * The meta object literal for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.PaperActionImpl <em>Paper Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.PaperActionImpl
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getPaperAction()
     * @generated
     */
    EClass PAPER_ACTION = eINSTANCE.getPaperAction();

    /**
     * The meta object literal for the '<em><b>Report</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAPER_ACTION__REPORT = eINSTANCE.getPaperAction_Report();

    /**
     * The meta object literal for the '{@link persons.tasks3.merger.mdsl.mergerDsl.impl.PaymentActionImpl <em>Payment Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.PaymentActionImpl
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getPaymentAction()
     * @generated
     */
    EClass PAYMENT_ACTION = eINSTANCE.getPaymentAction();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAYMENT_ACTION__AMOUNT = eINSTANCE.getPaymentAction_Amount();

    /**
     * The meta object literal for the '{@link persons.tasks3.merger.mdsl.mergerDsl.TimeUnit <em>Time Unit</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks3.merger.mdsl.mergerDsl.TimeUnit
     * @see persons.tasks3.merger.mdsl.mergerDsl.impl.MergerDslPackageImpl#getTimeUnit()
     * @generated
     */
    EEnum TIME_UNIT = eINSTANCE.getTimeUnit();

  }

} //MergerDslPackage
