/**
 * generated by Xtext 2.25.0
 */
package persons.tasks3.merger.mdsl.mergerDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Planning</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link persons.tasks3.merger.mdsl.mergerDsl.Planning#getName <em>Name</em>}</li>
 *   <li>{@link persons.tasks3.merger.mdsl.mergerDsl.Planning#getPersons <em>Persons</em>}</li>
 *   <li>{@link persons.tasks3.merger.mdsl.mergerDsl.Planning#getTasks <em>Tasks</em>}</li>
 * </ul>
 *
 * @see persons.tasks3.merger.mdsl.mergerDsl.MergerDslPackage#getPlanning()
 * @model
 * @generated
 */
public interface Planning extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see persons.tasks3.merger.mdsl.mergerDsl.MergerDslPackage#getPlanning_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link persons.tasks3.merger.mdsl.mergerDsl.Planning#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Persons</b></em>' containment reference list.
   * The list contents are of type {@link persons.tasks3.merger.mdsl.mergerDsl.Person}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Persons</em>' containment reference list.
   * @see persons.tasks3.merger.mdsl.mergerDsl.MergerDslPackage#getPlanning_Persons()
   * @model containment="true"
   * @generated
   */
  EList<Person> getPersons();

  /**
   * Returns the value of the '<em><b>Tasks</b></em>' containment reference list.
   * The list contents are of type {@link persons.tasks3.merger.mdsl.mergerDsl.Task}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasks</em>' containment reference list.
   * @see persons.tasks3.merger.mdsl.mergerDsl.MergerDslPackage#getPlanning_Tasks()
   * @model containment="true"
   * @generated
   */
  EList<Task> getTasks();

} // Planning
