/**
 * generated by Xtext 2.25.0
 */
package persons.tasks3.merger.mdsl.mergerDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link persons.tasks3.merger.mdsl.mergerDsl.Task#getAction <em>Action</em>}</li>
 *   <li>{@link persons.tasks3.merger.mdsl.mergerDsl.Task#getPersons <em>Persons</em>}</li>
 *   <li>{@link persons.tasks3.merger.mdsl.mergerDsl.Task#getPrio <em>Prio</em>}</li>
 *   <li>{@link persons.tasks3.merger.mdsl.mergerDsl.Task#getDl <em>Dl</em>}</li>
 *   <li>{@link persons.tasks3.merger.mdsl.mergerDsl.Task#getUnit <em>Unit</em>}</li>
 * </ul>
 *
 * @see persons.tasks3.merger.mdsl.mergerDsl.MergerDslPackage#getTask()
 * @model
 * @generated
 */
public interface Task extends EObject
{
  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(Action)
   * @see persons.tasks3.merger.mdsl.mergerDsl.MergerDslPackage#getTask_Action()
   * @model containment="true"
   * @generated
   */
  Action getAction();

  /**
   * Sets the value of the '{@link persons.tasks3.merger.mdsl.mergerDsl.Task#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(Action value);

  /**
   * Returns the value of the '<em><b>Persons</b></em>' reference list.
   * The list contents are of type {@link persons.tasks3.merger.mdsl.mergerDsl.Person}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Persons</em>' reference list.
   * @see persons.tasks3.merger.mdsl.mergerDsl.MergerDslPackage#getTask_Persons()
   * @model
   * @generated
   */
  EList<Person> getPersons();

  /**
   * Returns the value of the '<em><b>Prio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prio</em>' attribute.
   * @see #setPrio(int)
   * @see persons.tasks3.merger.mdsl.mergerDsl.MergerDslPackage#getTask_Prio()
   * @model
   * @generated
   */
  int getPrio();

  /**
   * Sets the value of the '{@link persons.tasks3.merger.mdsl.mergerDsl.Task#getPrio <em>Prio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prio</em>' attribute.
   * @see #getPrio()
   * @generated
   */
  void setPrio(int value);

  /**
   * Returns the value of the '<em><b>Dl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dl</em>' attribute.
   * @see #setDl(int)
   * @see persons.tasks3.merger.mdsl.mergerDsl.MergerDslPackage#getTask_Dl()
   * @model
   * @generated
   */
  int getDl();

  /**
   * Sets the value of the '{@link persons.tasks3.merger.mdsl.mergerDsl.Task#getDl <em>Dl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dl</em>' attribute.
   * @see #getDl()
   * @generated
   */
  void setDl(int value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * The literals are from the enumeration {@link persons.tasks3.merger.mdsl.mergerDsl.TimeUnit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see persons.tasks3.merger.mdsl.mergerDsl.TimeUnit
   * @see #setUnit(TimeUnit)
   * @see persons.tasks3.merger.mdsl.mergerDsl.MergerDslPackage#getTask_Unit()
   * @model
   * @generated
   */
  TimeUnit getUnit();

  /**
   * Sets the value of the '{@link persons.tasks3.merger.mdsl.mergerDsl.Task#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see persons.tasks3.merger.mdsl.mergerDsl.TimeUnit
   * @see #getUnit()
   * @generated
   */
  void setUnit(TimeUnit value);

} // Task
