/*
 * generated by Xtext 2.25.0
 */
package persons.tasks3.merger.mdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMergerDslScopeProvider extends DelegatingScopeProvider {
}
