/*
 * generated by Xtext 2.25.0
 */
package persons.tasks3.merger.mdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MergerDslUiModule extends  AbstractMergerDslUiModule {

	public MergerDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
		}
	
	
}
