/*
 * generated by Xtext 2.25.0
 */
package persons.tasks3.merger.mdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MergerDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("persons/tasks3/merger/mdsl/parser/antlr/internal/InternalMergerDsl.tokens");
	}
}
