/*
 * generated by Xtext 2.25.0
 */
package persons.tasks3.merger.mdsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMergerDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(persons.tasks3.merger.mdsl.mergerDsl.MergerDslPackage.eINSTANCE);
		return result;
	}
}
